default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: <%= ENV.fetch("DATABASE_USER") { `whoami`.strip } %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

production:
  <<: *default
  database: chorbee_production

staging:
  <<: *default
  database: chorbee_staging

development:
  <<: *default
  database: chorbee_development

test:
  <<: *default
  database: chorbee_test
